# Generated by Django 5.0.1 on 2024-01-16 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=250)),
                ('Mob_No', models.CharField(max_length=40)),
                ('Addr', models.CharField(max_length=255)),
                ('Type', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('mobile', models.CharField(max_length=255, unique=True)),
                ('pswd', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('Type', models.CharField(max_length=100)),
                ('Qantity', models.FloatField()),
                ('Date', models.DateField()),
                ('Rate', models.FloatField()),
                ('fk_customer_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userApp.customer')),
                ('fk_User_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userApp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PayRs', models.FloatField()),
                ('Date', models.DateField()),
                ('fk_customer_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userApp.customer')),
                ('fk_User_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userApp.user')),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='fk_User_Id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userApp.user'),
        ),
    ]
